{{- if .Values.volumes.create_PV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.PersistentVolumeTemplate.metadata.name | default (printf "%s-pv" .Values.fullname) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.volumes.PersistentVolumeTemplate.metadata.labels | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volumes.PersistentVolumeTemplate.spec.capacity.storage | default "1Gi" }}
  accessModes:
    {{- toYaml .Values.volumes.PersistentVolumeTemplate.spec.accessModes | nindent 2 }}
  storageClassName: {{ .Values.volumes.PersistentVolumeTemplate.spec.storageClassName | default "standard" }}
  hostPath:
    path: {{ .Values.volumes.PersistentVolumeTemplate.spec.hostPath.path | default "/mnt/disks/default" }}
{{- end }}
