{{- if .Values.volumes.create_PV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fullname }}-pv
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.volumes.labels | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volumes.PersistentVolumeTemplate.spec.capacity.storage }}
  accessModes:
    {{- toYaml .Values.volumes.PersistentVolumeTemplate.spec.accessModes | nindent 2 }}
  storageClassName: {{ .Values.volumes.PersistentVolumeTemplate.spec.storageClassName }}
  hostPath:
    path: {{ .Values.volumes.PersistentVolumeTemplate.spec.hostPath.path }}
{{- end }}
