{{- if .Values.volumes.create_PV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.PersistentVolume.metadata.name | default "node-app-pv" }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- toYaml .Values.volumes.PersistentVolume.metadata.labels | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volumes.PersistentVolume.spec.capacity.storage | default "1Gi" }}
  accessModes:
    {{- if .Values.volumes.PersistentVolume.spec.accessModes }}
    {{- toYaml .Values.volumes.PersistentVolume.spec.accessModes | nindent 2 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  storageClassName: {{ .Values.volumes.PersistentVolume.spec.storageClassName | default "manual" }}
  hostPath:
    path: {{ .Values.volumes.PersistentVolume.spec.hostPath.path | default "/mnt/data" }}
{{- end }}
