{{- if .Values.volumes.create_PVC }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.volumes.labels | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.volumes.PersistentVolumeClaimTemplate.spec.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.volumes.PersistentVolumeClaimTemplate.spec.resources.requests.storage }}
  storageClassName: {{ .Values.volumes.PersistentVolumeClaimTemplate.spec.storageClassName }}
{{- end }}
